runtime: python39

# Note: Saving credentials in environment variables is convenient, but not
# secure - consider a more secure solution such as
# Cloud Secret Manager (https://cloud.google.com/secret-manager) to help
# keep secrets safe.
env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/project-bangkit-352403:asia-southeast2:bangkit-tez
  DB_USER: master
  DB_PASS: 123
  DB_NAME: demo