# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  INSTANCE_HOST : 34.27.166.253
  DB_USER: root
  DB_PASS: 123
  DB_NAME: yourney
  DB_PORT: 3306
# [END gae_python37_cloudsql_config]
