# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: 
  CLOUD_SQL_DATABASE_NAME: yourney
  CLOUD_SQL_CONNECTION_NAME: 127.0.0.1
  JWT_SECRET:
# [END gae_python37_cloudsql_config]
